export type YogaCategory = "Pilates" | "Yoga" | "Stretching" | "Méditation" | "Barre";

export interface YogaExercise {
  id: string;
  title: string;
  category: YogaCategory;
  level: "Débutant" | "Intermédiaire" | "Avancé";
  coverImage: string;
  youtubeEmbedId: string;
  duration: number;
  calories: number;
  description: string;
  musclesTargeted: string[];
  benefits: string[];
  instructions: string[];
  tags: string[];
}

export interface YogaSession {
  id: string;
  title: string;
  category: YogaCategory;
  level: "Débutant" | "Intermédiaire" | "Avancé";
  coverImage: string;
  durationMin: number;
  calories: number;
  description: string;
  exerciseIds: string[];
  tag?: string;
}

export const YOGA_EXERCISES: YogaExercise[] = [
  // PILATES
  {
    id: "yoga-pilates-hundred",
    title: "The Hundred",
    category: "Pilates",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "AB9OhOJhM_U",
    duration: 10,
    calories: 55,
    description: "Exercice fondamental du Pilates qui renforce la sangle abdominale et améliore la coordination respiratoire.",
    musclesTargeted: ["Abdominaux", "Fléchisseurs de hanche", "Intercostaux"],
    benefits: ["Renforce le core", "Améliore la respiration", "Active la circulation"],
    instructions: [
      "Allongez-vous sur le dos, genoux pliés à 90°",
      "Levez la tête et les épaules du sol",
      "Tendez les bras le long du corps, paumes vers le bas",
      "Pompez les bras de haut en bas en respirant : 5 inspirations, 5 expirations",
      "Répétez 10 cycles pour atteindre 100 pompes",
    ],
    tags: ["core", "respiration", "débutant-avancé"],
  },
  {
    id: "yoga-pilates-rollup",
    title: "Roll Up",
    category: "Pilates",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "yeVFBkNs8dw",
    duration: 8,
    calories: 40,
    description: "Le Roll Up mobilise toute la colonne vertébrale et développe une force abdominale profonde.",
    musclesTargeted: ["Abdominaux", "Colonne vertébrale", "Ischio-jambiers"],
    benefits: ["Flexibilité de la colonne", "Force abdominale profonde", "Massage des vertèbres"],
    instructions: [
      "Allongez-vous sur le dos, bras tendus au-dessus de la tête",
      "Inspirez en levant les bras vers le plafond",
      "Expirez et déroulez la colonne vertèbre par vertèbre",
      "Atteignez les orteils en position assise",
      "Redescendez lentement en inversant le mouvement",
    ],
    tags: ["colonne", "flexibilité", "core"],
  },
  {
    id: "yoga-pilates-bridge",
    title: "Pilates Bridge",
    category: "Pilates",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "mSHU87zFAnU",
    duration: 8,
    calories: 35,
    description: "Le pont Pilates active les fessiers, les ischio-jambiers et stabilise le bassin.",
    musclesTargeted: ["Fessiers", "Ischio-jambiers", "Core", "Colonne"],
    benefits: ["Renforce les fessiers", "Soulage le bas du dos", "Améliore la posture"],
    instructions: [
      "Allongez-vous sur le dos, pieds à plat, genoux pliés",
      "Bras le long du corps, paumes vers le bas",
      "Inspirez pour préparer",
      "Expirez en décollant le bassin, vertèbre par vertèbre",
      "Tenez 3 secondes en haut, puis redescendez lentement",
    ],
    tags: ["fessiers", "posture", "dos"],
  },
  {
    id: "yoga-pilates-teaser",
    title: "Teaser",
    category: "Pilates",
    level: "Avancé",
    coverImage: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "LdCJdAlPbFc",
    duration: 12,
    calories: 70,
    description: "Le Teaser est le mouvement signature du Pilates. Il combine équilibre, force et contrôle total.",
    musclesTargeted: ["Abdominaux", "Fléchisseurs de hanche", "Équilibre"],
    benefits: ["Force abdominale maximale", "Équilibre", "Coordination"],
    instructions: [
      "Allongez-vous sur le dos, jambes tendues à 45°",
      "Bras tendus vers le haut",
      "Inspirez pour préparer",
      "Expirez en montant simultanément le buste et les jambes",
      "Formez un V avec votre corps, bras parallèles aux jambes",
      "Tenez 3 secondes puis redescendez doucement",
    ],
    tags: ["core avancé", "équilibre", "signature Pilates"],
  },
  // YOGA
  {
    id: "yoga-sun-salutation",
    title: "Salutation au Soleil A",
    category: "Yoga",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1603988363607-e1e4a66962c6?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "73sjOu0g58M",
    duration: 15,
    calories: 80,
    description: "Séquence fondamentale du yoga qui réveille le corps, synchronise le souffle et le mouvement.",
    musclesTargeted: ["Corps entier", "Dos", "Épaules", "Jambes"],
    benefits: ["Énergie matinale", "Flexibilité globale", "Pleine conscience"],
    instructions: [
      "Samasthiti : debout, pieds joints, mains en prière",
      "Inspiration : bras au ciel, regard en haut",
      "Expiration : flexion avant, mains au sol",
      "Inspiration : demi-flexion, dos plat",
      "Expiration : saut en planche, Chaturanga",
      "Inspiration : chien tête en haut",
      "Expiration : chien tête en bas, 5 respirations",
      "Sauter les pieds entre les mains, se relever",
    ],
    tags: ["fondamental", "matin", "énergie", "flow"],
  },
  {
    id: "yoga-warrior-i",
    title: "Guerrier I",
    category: "Yoga",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "k85GDnJ7PFg",
    duration: 10,
    calories: 45,
    description: "Le Guerrier I renforce les jambes et ouvre la poitrine, symbole de force et de grâce.",
    musclesTargeted: ["Quadriceps", "Fessiers", "Épaules", "Core"],
    benefits: ["Force des jambes", "Ouverture des hanches", "Stabilité"],
    instructions: [
      "Depuis Tadasana, écartez un grand pas en arrière",
      "Tournez le pied arrière à 45°",
      "Pliez le genou avant à 90°",
      "Levez les bras au ciel, regard en haut",
      "Tenez 5 respirations, changez de côté",
    ],
    tags: ["force", "équilibre", "hanches"],
  },
  {
    id: "yoga-child-pose",
    title: "Posture de l'Enfant",
    category: "Yoga",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "qZ-GM_iUJ6c",
    duration: 5,
    calories: 15,
    description: "Posture de repos et de récupération qui étire le dos et calme le système nerveux.",
    musclesTargeted: ["Dos", "Hanches", "Chevilles"],
    benefits: ["Relaxation profonde", "Étire le bas du dos", "Calme le mental"],
    instructions: [
      "À genoux, asseyez-vous sur les talons",
      "Penchez-vous en avant en tendant les bras",
      "Front posé sur le sol",
      "Relâchez complètement les épaules",
      "Respirez profondément 8 à 10 fois",
    ],
    tags: ["repos", "récupération", "dos", "calme"],
  },
  {
    id: "yoga-triangle",
    title: "Pose du Triangle",
    category: "Yoga",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1510894347713-fc3ed6fdf539?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "hBBLxiPzZNM",
    duration: 10,
    calories: 40,
    description: "Le Triangle étire et renforce les jambes, ouvre les hanches et améliore la stabilité latérale.",
    musclesTargeted: ["Ischio-jambiers", "Adducteurs", "Obliques", "Épaules"],
    benefits: ["Flexibilité latérale", "Ouverture des hanches", "Équilibre"],
    instructions: [
      "Écartez les pieds à 1m environ",
      "Tournez le pied droit à 90°, gauche à 45°",
      "Tendez les bras en T",
      "Inclinez vers la droite, main droite vers le tibia",
      "Bras gauche vers le ciel, regard vers la main",
      "Tenez 5 respirations, changez de côté",
    ],
    tags: ["étirement", "latéral", "hanches", "équilibre"],
  },
  // STRETCHING
  {
    id: "yoga-stretch-pigeon",
    title: "Pigeon Endormi",
    category: "Stretching",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "1VDrDV4zKSc",
    duration: 12,
    calories: 30,
    description: "Étirement profond des fessiers et des hanches. Idéal pour les runners et sportifs.",
    musclesTargeted: ["Fessiers", "Piriforme", "Fléchisseurs de hanche", "Ilio-tibial"],
    benefits: ["Libère les tensions des hanches", "Réduit les douleurs lombaires", "Récupération post-run"],
    instructions: [
      "En quadrupédie, amenez le genou droit vers la main droite",
      "Étendez la jambe gauche en arrière",
      "Abaissez les hanches vers le sol",
      "Penchez le buste en avant, front sur les mains",
      "Respirez profondément, tenez 60 à 90 secondes",
      "Changez de côté",
    ],
    tags: ["runners", "fessiers", "hanches", "récupération"],
  },
  {
    id: "yoga-stretch-hamstring",
    title: "Étirement Ischio-Jambiers",
    category: "Stretching",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "mnH0jGHIVH8",
    duration: 8,
    calories: 20,
    description: "Étirement essentiel post-course pour prévenir les blessures et améliorer la flexibilité.",
    musclesTargeted: ["Ischio-jambiers", "Mollets", "Bas du dos"],
    benefits: ["Prévention des blessures", "Récupération", "Flexibilité"],
    instructions: [
      "Assis sur le sol, jambes tendues devant vous",
      "Inspirez en grandissant la colonne",
      "Expirez en vous penchant vers l'avant",
      "Attrapez les pieds ou les mollets",
      "Tenez 45 secondes en respirant",
    ],
    tags: ["post-run", "ischio", "souplesse"],
  },
  {
    id: "yoga-stretch-hip-flexor",
    title: "Fente Basse — Fléchisseurs",
    category: "Stretching",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1593164842264-854604db2260?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "kHRJmGFamJo",
    duration: 8,
    calories: 20,
    description: "Étire les fléchisseurs de hanche souvent contractés après la course ou la position assise.",
    musclesTargeted: ["Fléchisseurs de hanche", "Psoas", "Quadriceps"],
    benefits: ["Posture améliorée", "Libère le bas du dos", "Mobilité des hanches"],
    instructions: [
      "En fente basse, genou arrière au sol",
      "Gardez le torse droit, bassin neutre",
      "Poussez doucement les hanches vers l'avant",
      "Option : levez les bras au ciel",
      "Tenez 45 secondes, changez de côté",
    ],
    tags: ["hanches", "posture", "psoas", "runners"],
  },
  // MÉDITATION
  {
    id: "yoga-meditation-478",
    title: "Respiration 4-7-8",
    category: "Méditation",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "gz4G31LGyog",
    duration: 8,
    calories: 10,
    description: "Technique de respiration puissante pour réduire le stress, améliorer le sommeil et calmer l'esprit.",
    musclesTargeted: ["Diaphragme", "Poumons"],
    benefits: ["Réduit l'anxiété", "Améliore le sommeil", "Régule le système nerveux"],
    instructions: [
      "Installez-vous confortablement, dos droit",
      "Fermez les yeux, relâchez les épaules",
      "Inspirez par le nez pendant 4 secondes",
      "Retenez votre souffle 7 secondes",
      "Expirez par la bouche pendant 8 secondes",
      "Répétez 4 cycles, puis augmentez progressivement",
    ],
    tags: ["stress", "sommeil", "calme", "souffle"],
  },
  {
    id: "yoga-meditation-body-scan",
    title: "Body Scan",
    category: "Méditation",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "QS2yDmWk0vs",
    duration: 15,
    calories: 10,
    description: "Méditation de pleine conscience qui parcourt le corps de la tête aux pieds pour relâcher les tensions.",
    musclesTargeted: ["Corps entier"],
    benefits: ["Relaxation profonde", "Pleine conscience", "Libère les tensions"],
    instructions: [
      "Allongez-vous en Savasana (sur le dos)",
      "Fermez les yeux, respirez naturellement",
      "Portez l'attention sur les orteils",
      "Remontez progressivement : pieds, jambes, bassin, ventre...",
      "Observez chaque zone sans jugement",
      "Terminez par quelques respirations profondes",
    ],
    tags: ["relaxation", "pleine conscience", "récupération"],
  },
  {
    id: "yoga-meditation-vipassana",
    title: "Méditation Pleine Conscience",
    category: "Méditation",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "inpok4MKVLM",
    duration: 20,
    calories: 12,
    description: "Méditation de pleine conscience centrée sur l'observation du souffle et des pensées sans attachement.",
    musclesTargeted: ["Mental"],
    benefits: ["Clarté mentale", "Gestion du stress", "Concentration"],
    instructions: [
      "Assis en tailleur ou sur une chaise, dos droit",
      "Posez les mains sur les genoux",
      "Observez votre souffle naturel",
      "Quand l'esprit s'égare, ramenez doucement l'attention",
      "Pratiquez sans jugement pendant 15 à 20 minutes",
    ],
    tags: ["mental", "concentration", "vipassana"],
  },
  // BARRE
  {
    id: "yoga-barre-plie",
    title: "Plié au Sol",
    category: "Barre",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "7giT3pK8Kms",
    duration: 10,
    calories: 50,
    description: "Inspiré du ballet, le plié renforce l'intérieur des cuisses, les fessiers et améliore la posture.",
    musclesTargeted: ["Adducteurs", "Fessiers", "Quadriceps", "Core"],
    benefits: ["Raffermit l'intérieur des cuisses", "Posture élégante", "Force des jambes"],
    instructions: [
      "Debout, pieds à 45° en position de ballet (1ère ou 2ème position)",
      "Mains sur les hanches ou sur un support",
      "Abaissez lentement en pliant les genoux vers l'extérieur",
      "Maintenez le dos droit, montez sur les orteils en option",
      "Remontez en contractant les fessiers",
      "30 répétitions lentes",
    ],
    tags: ["ballet", "intérieur cuisses", "posture", "fessiers"],
  },
  {
    id: "yoga-barre-arabesque",
    title: "Arabesque",
    category: "Barre",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "NN_JWQN83IU",
    duration: 10,
    calories: 45,
    description: "Exercice de barre classique qui développe l'équilibre, la force des fessiers et la grâce du mouvement.",
    musclesTargeted: ["Fessiers", "Dos", "Core", "Mollets"],
    benefits: ["Équilibre", "Force des fessiers", "Coordination"],
    instructions: [
      "Debout face à la barre, une main d'appui",
      "Penchez légèrement le buste vers l'avant",
      "Soulevez une jambe tendue derrière vous",
      "Maintenez le bassin équilibré et les hanches parallèles",
      "Montez et descendez la jambe 15-20 fois",
      "Changez de côté",
    ],
    tags: ["ballet", "équilibre", "fessiers", "grâce"],
  },
  {
    id: "yoga-barre-releve",
    title: "Relevé & Équilibre",
    category: "Barre",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=600&h=340&fit=crop&auto=format&q=80",
    youtubeEmbedId: "gBcT4oQJi8c",
    duration: 8,
    calories: 35,
    description: "Le relevé sur pointes renforce les mollets et améliore l'équilibre, exercice de base de la barre.",
    musclesTargeted: ["Mollets", "Chevilles", "Core", "Pieds"],
    benefits: ["Mollets sculptés", "Équilibre amélioré", "Force des pieds"],
    instructions: [
      "Debout, pieds joints ou 1ère position",
      "Montez sur les pointes des pieds lentement",
      "Tenez l'équilibre 3 secondes en haut",
      "Redescendez avec contrôle",
      "Version avancée : sur un pied",
      "30 répétitions",
    ],
    tags: ["mollets", "équilibre", "ballet", "pieds"],
  },
];

export const YOGA_CATEGORIES: YogaCategory[] = [
  "Pilates", "Yoga", "Stretching", "Méditation", "Barre",
];

export const YOGA_CATEGORY_COLORS: Record<YogaCategory, string> = {
  Pilates: "#E8A598",
  Yoga: "#9B7B6E",
  Stretching: "#8BAB8B",
  Méditation: "#A8C5DA",
  Barre: "#C4A882",
};

export const YOGA_SESSIONS: YogaSession[] = [
  {
    id: "ys-morning-flow",
    title: "Flow Matinal",
    category: "Yoga",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1603988363607-e1e4a66962c6?w=600&h=340&fit=crop&auto=format&q=80",
    durationMin: 20,
    calories: 90,
    description: "Réveillez votre corps en douceur avec cette séquence de yoga matinale énergisante.",
    exerciseIds: ["yoga-sun-salutation", "yoga-warrior-i", "yoga-triangle"],
    tag: "POPULAIRE",
  },
  {
    id: "ys-pilates-core",
    title: "Core Pilates Express",
    category: "Pilates",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=340&fit=crop&auto=format&q=80",
    durationMin: 30,
    calories: 150,
    description: "Programme Pilates intensif pour renforcer votre sangle abdominale et votre posture.",
    exerciseIds: ["yoga-pilates-hundred", "yoga-pilates-rollup", "yoga-pilates-bridge", "yoga-pilates-teaser"],
    tag: "RENFORCEMENT",
  },
  {
    id: "ys-recovery",
    title: "Récupération Active",
    category: "Stretching",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=600&h=340&fit=crop&auto=format&q=80",
    durationMin: 25,
    calories: 70,
    description: "Séance de récupération idéale après un entraînement intense. Étirements profonds et relaxation.",
    exerciseIds: ["yoga-stretch-pigeon", "yoga-stretch-hamstring", "yoga-stretch-hip-flexor", "yoga-child-pose"],
    tag: "RÉCUPÉRATION",
  },
  {
    id: "ys-meditation-calm",
    title: "Paix Intérieure",
    category: "Méditation",
    level: "Débutant",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=340&fit=crop&auto=format&q=80",
    durationMin: 20,
    calories: 30,
    description: "Séance de méditation guidée pour calmer le mental et retrouver la sérénité.",
    exerciseIds: ["yoga-meditation-478", "yoga-meditation-body-scan", "yoga-meditation-vipassana"],
    tag: "ANTI-STRESS",
  },
  {
    id: "ys-barre-sculpt",
    title: "Barre Sculpture",
    category: "Barre",
    level: "Intermédiaire",
    coverImage: "https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=600&h=340&fit=crop&auto=format&q=80",
    durationMin: 35,
    calories: 160,
    description: "Sculplez votre silhouette avec cette séance de barre inspirée du ballet.",
    exerciseIds: ["yoga-barre-plie", "yoga-barre-arabesque", "yoga-barre-releve"],
    tag: "SCULPTURE",
  },
];

export const YOGA_MOTIVATION_QUOTES = [
  "Le yoga n'est pas une religion. C'est une science, la science du bien-être.",
  "Respire. Tu es ici. Tu es vivant. C'est tout ce qui compte.",
  "Chaque séance te rapproche de la meilleure version de toi-même.",
  "La flexibilité du corps reflète la flexibilité de l'esprit.",
  "Ton tapis est ton sanctuaire. Prends soin de toi.",
  "La paix commence par une seule respiration.",
];
